wheesh/users/urls.py
from django.urls import path
from users.views import (
    EmailVerificationView,
    UserLoginView,
    UserLogoutView,
    UserPasswordResetCompleteView,
    UserPasswordResetConfirmView,
    UserPasswordResetDoneView,
    UserPasswordResetView,
    UserProfileView,
    UserRegistrationView,
    VerificationExpiredView,
)

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('verify/<str:email>/<int:code>/', EmailVerificationView.as_view(), name='verify'),
    path('expired/<str:email>/<int:code>/', VerificationExpiredView.as_view(), name='verification_expired'),
    path('password-reset/', UserPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('passsword-reset/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

wheesh/wheesh/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from wishlists.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('', include('wishlists.urls', namespace='wishlists')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wheesh/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.timezone import now


class User(AbstractUser):
    email = models.EmailField(unique=True)
    image = models.ImageField(upload_to='users_images', null=True, blank=True)
    email_verified = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.username

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'


class EmailVerification(models.Model):
    code = models.SmallIntegerField()
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    expiration = models.DateTimeField()

    def is_expired(self) -> bool:
        return now() >= self.expiration

    def __str__(self) -> str:
        return f'EmailVerificationObject for {self.user.email}'

    class Meta:
        verbose_name = 'верификация эл. почты'
        verbose_name_plural = 'верификации эл. почты'
        unique_together = ('code', 'user')

wheesh/users/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordResetForm,
    SetPasswordForm,
    UserChangeForm,
    UserCreationForm,
)
from users.models import User
from users.utils import (
    create_verification_object,
    email_verification_service,
    generate_verification_code,
)


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите имя пользователя'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Введите пароль'}))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите имя пользователя'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Введите адрес эл. почты'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Повторите пароль'}))

    def save(self, commit = True, is_final = True):
        user =  super().save(commit=True)

        if is_final:  # TODO: fix double form saving in users.views.UserRegistrationView.form_valid
            code = generate_verification_code()
            create_verification_object(user.id, code)

            email_verification_service.send_verification_web(user.id, user.email, user.username, code)

        return user

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control', 'id': 'profilePicInput', 'onchange': 'previewImage(event)'}), required=False)
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control-readonly form-control', 'id': 'disabledTextInput', 'readonly': True}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control-readonly form-control', 'id': 'disabledTextInput', 'readonly': True}))


    class Meta:
        model = User
        fields = ('image', 'first_name', 'last_name', 'username', 'email')


class UserForgotPasswordForm(PasswordResetForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Введите адрес эл. почты'}))

class UserSetNewPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Введите новый пароль', 'autocomplete': False}), label='Введите новый пароль')
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Повторите новый пароль', 'autocomplete': False}), label='Повторите новый пароль')

wheesh/users/views.py
from typing import Any

from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models.base import Model
from django.http import HttpResponseNotFound, HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView

from common.mixins import CommonContextMixin
from users.forms import (
    UserForgotPasswordForm,
    UserLoginForm,
    UserProfileForm,
    UserRegistrationForm,
    UserSetNewPasswordForm,
)
from users.models import EmailVerification, User
from users.utils import (
    create_verification_object,
    email_verification_service,
    generate_verification_code,
)
from wishlists.models import Wishlist


class UserRegistrationView(CommonContextMixin, SuccessMessageMixin, CreateView):
    template_name = 'users/register.html'
    title = 'Регистрация - Wheesh'
    form_class = UserRegistrationForm
    model = User
    success_url = reverse_lazy('users:login')
    success_message = 'Вы успешно зарегистрировались!\nОбязательно подтвердите свою электронную почту перед входом!'

    def form_valid(self, form):
        user = form.save(is_final=False)
        Wishlist.objects.create(title='Основной вишлист', user=user)
        return super().form_valid(form)


class UserLoginView(CommonContextMixin, LoginView):
    template_name = 'users/login.html'
    title = 'Вход - Wheesh'
    next_page = '/'
    form_class = UserLoginForm
    model = User

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.email_verified:
                login(self.request, user)
                return redirect(self.get_success_url())
            else:
                messages.warning(self.request, "Сначала подтвердите свою почту, перейдя по ссылке в письме!")
                return self.form_invalid(form)
        else:
            return self.form_invalid(form)


class UserLogoutView(LoginRequiredMixin, LogoutView):
    next_page = '/'


class UserProfileView(CommonContextMixin, LoginRequiredMixin, UpdateView):
    template_name = 'users/profile.html'
    title = 'Профиль - Wheesh'
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self) -> Model:
        return self.model.objects.get(pk=self.request.user.pk)

    def get_form_kwargs(self) -> dict[str, Any]:
        kwargs: dict[str, Any] = super().get_form_kwargs()

        if self.request.method in ("POST", "PUT"):
            kwargs.update(
                {
                    "data": self.request.POST,
                    "files": self.request.FILES,
                }
            )

        return kwargs


class EmailVerificationView(CommonContextMixin, TemplateView):
    title = 'Подтверждение электронной почты - Wheesh'
    template_name = 'users/email_verification.html'

    def get(self, request, *args, **kwargs):
        code = kwargs['code']
        email = kwargs['email']
        user = User.objects.get(email=email)
        email_verification = EmailVerification.objects.filter(code=code, user=user)
        verification_expired = email_verification.last().is_expired()

        if email_verification.exists():
            if not verification_expired:
                user.email_verified = True
                user.save()
                return super().get(request, *args, **kwargs)
            else:
                return HttpResponseRedirect(reverse('users:verification_expired', args=(email, code)))

        else:
            return HttpResponseNotFound('Такой ссылки не существует')


class VerificationExpiredView(CommonContextMixin, SuccessMessageMixin, TemplateView):
    title = 'Ссылка недействительна - Wheesh'
    template_name = 'users/verification_expired.html'

    def get(self, request, *args, **kwargs):
        email = kwargs['email']
        user = User.objects.filter(email=email)
        if user.exists():
            user = user.last()
            if user.email_verified:
                return HttpResponseRedirect(reverse('users:profile'))

            code = generate_verification_code()
            create_verification_object(user.id, code)
            email_verification_service.send_verification_web(user.id, user.email, user.username, code)
            return super().get(request, *args, **kwargs)
        else:
            return HttpResponseNotFound('Такой ссылки не существует')



class UserPasswordResetView(CommonContextMixin, PasswordResetView):
    title = 'Запрос восстановления пароля - Wheesh'
    template_name = 'users/password_reset.html'
    form_class = UserForgotPasswordForm
    success_url = reverse_lazy('users:password_reset_done')
    subject_template_name = 'users/email/password_subject_reset_mail.txt'
    email_template_name = 'users/email/password_reset_mail.html'


class UserPasswordResetDoneView(CommonContextMixin, PasswordResetDoneView):
    title = 'Запрос на восстановление отправлен - Wheesh'
    template_name = 'users/password_reset_done.html'


class UserPasswordResetConfirmView(CommonContextMixin, PasswordResetConfirmView):
    title = 'Сброс пароля - Wheesh'
    template_name = 'users/password_reset_confirm.html'
    success_url = reverse_lazy('users:password_reset_complete')
    form_class = UserSetNewPasswordForm


class UserPasswordResetCompleteView(CommonContextMixin, PasswordResetCompleteView):
    title = 'Пароль успешно изменен - Wheesh'
    template_name = 'users/password_reset_complete.html'

wheesh/users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Registration page" />
        <meta name="keywords" content="signup, registration, wheesh" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
              crossorigin="anonymous" />
        {% block css %}
        {% endblock css %}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Rubik"
              rel="stylesheet" />
        <link rel="shortcut icon"
              type="image/png"
              href="{% static 'favicon.ico' %}" />
        <title>{{ title }}</title>
    </head>
    <body>
        {% block content %}
        {% endblock content %}
        <!-- Bootstrap JS -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
                crossorigin="anonymous"></script>
    </body>
</html>

wheesh/users/templates/users/email_verification.html
{% extends "users/base.html" %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static "vendor/css/email_verification.css" %}" />
{% endblock css %}
{% block content %}
  <div class="container">
    <div class="row justify-content-center align-items-center vh-100">
      <div class="col-md-7 col-lg-4">
        <div class="card shadow border-0">
          <div class="card-body p-4">
            <h3 class="text-center mb-4">
              <b>Whee</b>sh
            </h3>
            <p class="text-center mt-3 mb-3 h5">Ваш аккаунт успешно активирован!</p>
            <div class="d-grid mb-3">
              <a href="{% url "users:login" %}" class="btn btn-purple">Войти</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

wheesh/users/templates/users/login.html
{% extends "users/base.html" %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static "vendor/css/login.css" %}" />
{% endblock css %}
{% block content %}
  <div class="container">
    <div class="row justify-content-center align-items-center vh-100">
      <div class="col-md-7 col-lg-4">
        <div class="card shadow border-0">
          <div class="card-body p-4">
            <h3 class="text-center mb-4">
              <b>Whee</b>sh
            </h3>
            <form action="{% url "users:login" %}" method="post">
              {% csrf_token %}
              {% if form.errors %}<div class="alert alert-danger">{{ form.non_field_errors }}</div>{% endif %}
              {% if messages %}
                {% for message in messages %}<div class="alert alert-{{ message.tags }} text-center">{{ message }}</div>{% endfor %}
              {% endif %}
              <div class="mb-3">
                <label for="{{ form.username.id_for_label }}" class="form-label">Имя пользователя</label>
                {{ form.username }}
              </div>
              <div class="mb-3">
                <label for="{{ form.password.id_for_label }}" class="form-label">Пароль</label>
                {{ form.password }}
              </div>
              <div class="d-grid mb-3">
                <button type="submit" class="btn btn-purple">Войти</button>
              </div>
              <div class="text-center">
                <a href="{% url "users:password_reset" %}"
                   class="text-decoration-none text-secondary">Забыли пароль?</a>
              </div>
            </form>
            <div class="text-center mt-3">
              <p class="text-secondary mb-0">
                Нет аккаунта?
                <a href="{% url "users:register" %}"
                   class="text-decoration-none text-purple">Регистрация</a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

wheesh/users/templates/users/password_reset.html
{% extends "users/base.html" %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static "vendor/css/password_reset_common.css" %}" />
{% endblock css %}
{% block content %}
  <div class="container">
    <div class="row justify-content-center align-items-center vh-100">
      <div class="col-md-7 col-lg-4">
        <div class="card shadow border-0">
          <div class="card-body p-4">
            <h3 class="text-center mb-4">
              <b>Whee</b>sh
            </h3>
            <form method="post">
              {% csrf_token %}
              {% if form.errors %}<div class="alert alert-danger">{{ form.non_field_errors }}</div>{% endif %}
              <div class="mb-3 text-center">
                <label for="{{ form.email.id_for_label }}" class="form-label text-center">Электронная почта</label>
                {{ form.email }}
              </div>
              <div class="d-grid mb-3">
                <button type="submit" class="btn btn-purple">Сбросить пароль</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

wheesh/users/templates/users/password_reset_complete.html
{% extends "users/base.html" %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static "vendor/css/password_reset_common.css" %}" />
{% endblock css %}
{% block content %}
  <div class="container">
    <div class="row justify-content-center align-items-center vh-100">
      <div class="col-md-7 col-lg-4">
        <div class="card shadow border-0">
          <div class="card-body p-4">
            <h3 class="text-center mb-4">
              <b>Whee</b>sh
            </h3>
            <p class="text-center mt-3 mb-3 h5">Ваш пароль успешно изменён!</p>
            <div class="d-grid mb-3">
              <a href="{% url "users:login" %}" class="btn btn-purple">Войти</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

wheesh/users/templates/users/password_reset_confirm.html
{% extends "users/base.html" %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static "vendor/css/password_reset_common.css" %}" />
{% endblock css %}
{% block content %}
  <div class="container">
    <div class="row justify-content-center align-items-center vh-100">
      <div class="col-md-7 col-lg-4">
        <div class="card shadow border-0">
          <div class="card-body p-4">
            <h3 class="text-center mb-4">
              <b>Whee</b>sh
            </h3>
            <form method="post">
              {% csrf_token %}
              {% if form.errors %}<div class="alert alert-danger">{{ form.errors }}</div>{% endif %}
              {% for field in form %}
                <div class="mb-3 text-center">
                  <label for="{{ field.id_for_label }}" class="form-label text-center">{{ field.label }}</label>
                  {{ field }}
                </div>
              {% endfor %}
              <div class="d-grid mb-3">
                <button type="submit" class="btn btn-purple">Сбросить пароль</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

wheesh/users/templates/users/password_reset_done.html
{% extends "users/base.html" %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static "vendor/css/password_reset_common.css" %}" />
{% endblock css %}
{% block content %}
  <div class="container">
    <div class="row justify-content-center align-items-center vh-100">
      <div class="col-md-7 col-lg-8">
        <div class="card shadow border-0">
          <div class="card-body p-4">
            <h3 class="text-center mb-4">
              <b>Whee</b>sh
            </h3>
            <p class="text-center mt-3 mb-3 h5">
              Отправили инструкции по восстановлению на указанную почту. Если аккаунт с такой почтой существует, то письмо вот-вот придёт ;)
            </p>
            <p class="text-center text-secondary mt-3 mb-3 h6">
              Если письмо не пришло, проверьте папку "спам" и корректность указанной почты.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

wheesh/users/templates/users/profile.html
{% extends "wishlists/base.html" %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static "vendor/css/profile.css" %}" />
{% endblock css %}
{% block content %}
  <div class="container my-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card shadow border-0">
          <div class="card-body p-4">
            <form action='{% url 'users:profile' %}'
                  method='post'
                  enctype="multipart/form-data">
              {% csrf_token %}
              {% if form.errors %}<div class="alert alert-danger">{{ form.errors }}</div>{% endif %}
              <div class="mb-3 text-center">
                <img id="profile-pic" src="{% if user.image %}{{ user.image.url }}{% else %}{% static "vendor/img/user-image-placeholder.png" %}{% endif %}" alt="User Avatar" class="rounded-circle mb-3" width="150" height="150" />
                <div class="mb-2">{{ form.image }}</div>
              </div>
              <div class="mb-3">
                <div class="mb-3">
                  <label for="{{ form.username.id_for_label }}" class="form-label">Имя пользователя</label>
                  {{ form.username }}
                </div>
                <div class="mb-3">
                  <label for="email" class="{{ form.email.id_for_label }}">Адрес электронной почты</label>
                  {{ form.email }}
                </div>
              </div>
              <!-- Save button -->
              <div class="d-grid">
                <button type="submit" class="btn btn-purple">Сохранить изменения</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}
{% block scripts %}
  <script>
  function previewImage(event) {
    const reader = new FileReader();
    reader.onload = function () {
      const output = document.getElementById("profile-pic");
      output.src = reader.result;
    };
    reader.readAsDataURL(event.target.files[0]);
  }
  </script>
{% endblock scripts %}

wheesh/users/templates/users/register.html
{% extends "users/base.html" %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static "vendor/css/register.css" %}" />
{% endblock css %}
{% block content %}
  <div class="container">
    <div class="row justify-content-center align-items-center vh-100">
      <div class="col-md-7 col-lg-5">
        <div class="card bg-white shadow border-0">
          <div class="card-body p-4">
            <h3 class="text-center mb-4">
              <b>Whee</b>sh
            </h3>
            <form action={% url "users:register" %} method="post">
              {% csrf_token %}
              <!-- Username input -->
              {% if form.errors %}<div class="alert alert-danger">{{ form.errors }}</div>{% endif %}
              <div class="mb-3">
                <label for="{{ form.username.id_for_label }}" class="form-label">Имя пользователя</label>
                {{ form.username }}
              </div>
              <!-- Email input -->
              <div class="mb-3">
                <label for="{{ form.email.id_for_label }}" class="form-label">Адрес электронной почты</label>
                {{ form.email }}
              </div>
              <!-- Password input -->
              <div class="mb-3">
                <label for="{{ form.password1.id_for_label }}" class="form-label">Пароль</label>
                {{ form.password1 }}
              </div>
              <!-- Confirm Password input -->
              <div class="mb-3">
                <label for="{{ form.password2.id_for_label }}" class="form-label">Подтвердите пароль</label>
                {{ form.password2 }}
              </div>
              <!-- Submit button -->
              <div class="d-grid mb-3">
                <button type="submit" class="btn btn-purple">Регистрация</button>
              </div>
            </form>
            <!-- Already have an account? -->
            <div class="text-center mt-3">
              <p class="text-secondary mb-0">
                Уже есть аккаунт?
                <a href="{% url "users:login" %}"
                   class="text-decoration-none text-purple">Войти</a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

wheesh/users/templates/users/verification_expired.html
{% extends "users/base.html" %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static "vendor/css/verification_expired.css" %}" />
{% endblock css %}
{% block content %}
  <div class="container">
    <div class="row justify-content-center align-items-center vh-100">
      <div class="col-md-7 col-lg-4">
        <div class="card shadow border-0">
          {% if messages %}
            <div class="alert alert-success">
              {% for message in messages %}{{ message }}{% endfor %}
            </div>
          {% endif %}
          <div class="card-body p-4">
            <h3 class="text-center mb-4">
              <b>Whee</b>sh
            </h3>
            <p class="text-center text-secondary mt-3 mb-3 h6">Срок подтверждения этой ссылки истёк... ( ._.)</p>
            {% comment %} TODO: add button to resend it (3 emails per hour!!!) {% endcomment %}
            <p class="text-center mt-3 mb-3 h5">Но новая уже летит вам на почту, проверяйте!</p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}