wheesh/users/urls.py
from django.urls import path
from users.views import (
    EmailVerificationView,
    UserLoginView,
    UserLogoutView,
    UserPasswordResetCompleteView,
    UserPasswordResetConfirmView,
    UserPasswordResetDoneView,
    UserPasswordResetView,
    UserProfileView,
    UserRegistrationView,
    VerificationExpiredView,
)

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('verify/<str:email>/<int:code>/', EmailVerificationView.as_view(), name='verify'),
    path('expired/<str:email>/<int:code>/', VerificationExpiredView.as_view(), name='verification_expired'),
    path('password-reset/', UserPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('passsword-reset/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

wheesh/wheesh/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from wishlists.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('', include('wishlists.urls', namespace='wishlists')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wheesh/wishlists/urls.py
from django.urls import path

from .views import (
    DeletePresentView,
    EditPresentView,
    ManagePresentReservationView,
    NewPresentView,
    PersonalWishlistView,
    ReservationsView,
    WishlistView,
)

app_name = 'wishlists'

urlpatterns = [
    path('personal/', PersonalWishlistView.as_view(), name='personal'),
    path('reserved/', ReservationsView.as_view(), name='reservations'),
    path('personal/present/new/', NewPresentView.as_view(), name='new_item'),
    path('personal/present/<int:pk>/edit/', EditPresentView.as_view(), name='edit_item'),
    path('personal/present/<int:pk>/delete/', DeletePresentView.as_view(), name='delete_item'),
    path('present/<int:present_id>/reserve', ManagePresentReservationView.as_view(), name='manage_reservation'),
    path('<str:wishlist_slug>/', WishlistView.as_view(), name='other'),
]

wheesh/wishlists/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from short_url import UrlEncoder

encoder = UrlEncoder(alphabet='mh8EfAByDnXqHFajGb9eT3r24utP7gvJdw6ZK5zMkURsWCYScVNpx')


class Wishlist(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='wishlists_images', null=True, blank=True)
    event_date = models.DateField(null=True, blank=True)
    user = models.ForeignKey('users.User', on_delete=models.CASCADE)
    slug_url = models.CharField(max_length=255, blank=True, unique=True)


    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.slug_url:
            self.slug_url = encoder.encode_url(self.pk)
            self.save(update_fields=['slug_url'])


    def __str__(self) -> str:
        return f'{self.title} ({self.user})'


    class Meta:
        verbose_name = 'вишлист'
        verbose_name_plural = 'вишлисты'



class Present(models.Model):
    title = models.CharField(max_length=40)
    description = models.TextField(max_length=40, null=True, blank=True)
    image = models.ImageField(upload_to='presents_images', null=True, blank=True)
    link = models.URLField()
    price = models.DecimalField(max_digits=9, decimal_places=2, null=True, blank=True)
    reserved_by = models.ForeignKey('users.User', on_delete=models.CASCADE, related_name='reserved_presents', default=None, null=True, blank=True)
    wishlist = models.ForeignKey(Wishlist, on_delete=models.CASCADE, related_name='presents')
    user = models.ForeignKey('users.User', on_delete=models.CASCADE)


    def __str__(self) -> str:
        return self.title


    class Meta:
        verbose_name = 'подарок'
        verbose_name_plural = 'подарки'

wheesh/wishlists/forms.py
from django import forms
from wishlists.models import Present


class NewPresentForm(forms.ModelForm):
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control', 'id': 'profilePicInput', 'onchange': 'previewImage(event)'}), required=False)
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите название подарка (макс. 40 символов)'}), max_length=40)
    description = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите краткое описание/пожелание (макс. 40 символов)'}), required=False, max_length=40)
    link = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ссылка на подарок'}))
    price = forms.DecimalField(widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Введите цену подарка (в рублях)'}), max_digits=9, decimal_places=2, required=False)


    class Meta:
        model = Present
        fields = ('image', 'title', 'description', 'link', 'price')


class EditPresentForm(forms.ModelForm):
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control', 'id': 'profilePicInput', 'onchange': 'previewImage(event)'}), required=False)
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите название подарка (макс. 40 символов)'}), max_length=40)
    description = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите краткое описание/пожелание (макс. 40 символов)'}), required=False, max_length=40)
    link = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ссылка на подарок'}))
    price = forms.DecimalField(widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Введите цену подарка (в рублях)'}), max_digits=9, decimal_places=2, required=False)


    class Meta:
        model = Present
        fields = ('image', 'title', 'description', 'link', 'price')

wheesh/wishlists/views.py
from typing import Any

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Prefetch
from django.db.models.query import Q, QuerySet
from django.http import HttpResponseNotFound, HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    ListView,
    TemplateView,
    UpdateView,
    View,
)

from common.mixins import CommonContextMixin, OwnershipRequiredMixin
from wishlists.forms import EditPresentForm, NewPresentForm
from wishlists.models import Present, Wishlist


class IndexView(CommonContextMixin, TemplateView):
    template_name = 'wishlists/index.html'
    title = 'Wheesh'


class PersonalWishlistView(CommonContextMixin, LoginRequiredMixin, ListView):
    template_name = 'wishlists/personal_wishlist.html'
    model = Wishlist
    context_object_name = 'wishlist'
    title = 'Мой вишлист - Wheesh'

    def get_queryset(self) -> QuerySet[Any]:
        wishlist = Wishlist.objects.filter(Q(user_id=self.request.user.id) & Q(title='Основной вишлист'))
        if wishlist.exists():
            self.__wishlist = wishlist.first()
            presents_queryset = self.__wishlist.presents.all().order_by('-pk')

            return presents_queryset

        self.__wishlist = Wishlist.objects.none()
        return self.__wishlist


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['wishlist_instance'] = self.__wishlist

        return context


class WishlistView(CommonContextMixin, LoginRequiredMixin, ListView):
    template_name = 'wishlists/wishlist.html'
    model = Wishlist
    context_object_name = 'wishlist'

    def get(self, request, *args, **kwargs):
        wishlist = Wishlist.objects.filter(slug_url=self.kwargs['wishlist_slug'])
        if wishlist.exists():
            self.__wishlist = wishlist.first()
            if self.__wishlist.user == self.request.user:
                return redirect('wishlists:personal')

            return super().get(request, *args, **kwargs)
        else:
            return HttpResponseNotFound('Такого вишлиста не существует ( ._.\')')

    def get_queryset(self) -> QuerySet[Any]:
        self.title = f'{self.__wishlist.user.username} - {self.__wishlist.title}'
        presents_queryset = self.__wishlist.presents.order_by('-pk')

        return presents_queryset


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['wishlist_instance'] = self.__wishlist

        return context


class NewPresentView(CommonContextMixin, LoginRequiredMixin, CreateView):
    template_name = 'wishlists/new_item.html'
    title = 'Добавить новый подарок - Wheesh'
    form_class = NewPresentForm
    model = Present
    success_url = reverse_lazy('wishlists:personal')

    def form_valid(self, form):
        present = form.save(commit=False)
        user = self.request.user

        present.wishlist = Wishlist.objects.get(Q(user_id=self.request.user.id) & Q(title='Основной вишлист'))
        present.user = user
        present.save()

        return super().form_valid(form)

    def get_form_kwargs(self) -> dict[str, Any]:
        kwargs: dict[str, Any] = super().get_form_kwargs()

        if self.request.method in ("POST", "PUT"):
            kwargs.update(
                {
                    "data": self.request.POST,
                    "files": self.request.FILES,
                }
            )

        return kwargs


class EditPresentView(OwnershipRequiredMixin, CommonContextMixin, UpdateView):
    template_name = 'wishlists/edit_item.html'
    title = 'Изменить подарок - Wheesh'
    form_class = EditPresentForm
    model = Present
    success_url = reverse_lazy('wishlists:personal')
    forbidden_message = 'Вы не можете редактировать этот подарок'

    def get_form_kwargs(self) -> dict[str, Any]:
        kwargs: dict[str, Any] = super().get_form_kwargs()

        if self.request.method in ("POST", "PUT"):
            kwargs.update(
                {
                    "data": self.request.POST,
                    "files": self.request.FILES,
                }
            )

        return kwargs


class DeletePresentView(OwnershipRequiredMixin, CommonContextMixin, DeleteView):
    model = Present
    success_url = reverse_lazy('wishlists:personal')
    forbidden_message = 'Вы не можете удалить этот подарок'


class ManagePresentReservationView(View):
    def get(self, request, present_id):  # TODO: make it POST request
        present = Present.objects.filter(pk=present_id)

        if present.exists():
            present = present.first()

            if present.reserved_by:
                present.reserved_by = None
            else:
                present.reserved_by = request.user

            present.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        return HttpResponseNotFound('Такого подарка не существует')


class ReservationsView(CommonContextMixin, LoginRequiredMixin, ListView):
    template_name = 'wishlists/reservations.html'
    title = 'Я дарю - Wheesh'
    model = Present
    context_object_name = 'wishlists'

    def get_queryset(self) -> QuerySet[Any]:
        user = self.request.user

        return Wishlist.objects.filter(presents__reserved_by=user).distinct().prefetch_related(
            Prefetch(
                'presents',
                queryset=Present.objects.filter(reserved_by=user),
                to_attr='reserved_presents'
            )
        )

wheesh/wishlists/templates/wishlists/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description"
          content="Wheesh - Платформа для создания и обмена списками желаний" />
    <meta name="keywords" content="список желаний, подарки, обмен, сюрприз" />
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossorigin="anonymous" />
    <link rel="shortcut icon"
          type="image/png"
          href="{% static 'favicon.ico' %}" />
    <!-- Custom CSS -->
    {% block css %}
    {% endblock css %}
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;600"
          rel="stylesheet" />
    <title>{{ title }}</title>
  </head>
  <body class="d-flex flex-column min-vh-100">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary border-bottom sticky-top">
      <div class="container-fluid container-lg">
        <a class="navbar-brand" href="{% url "index" %}"><b>Whee</b>sh</a>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarContent"
                aria-controls="navbarContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarContent">
          {% if user.is_authenticated %}
            <ul class="navbar-nav mb-0 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.url_name == 'personal' %}active{% endif %}"
                   href="{% url "wishlists:personal" %}">Я хочу</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.url_name == 'reservations' %}active{% endif %}"
                   href="{% url "wishlists:reservations" %}">Я дарю</a>
              </li>
            </ul>
          {% endif %}
          {% if user.is_authenticated %}
            <ul class="navbar-nav mb-2 mb-lg-0 ms-auto">
              <li class="nav-item d-none d-lg-block">
                <div class="btn-group">
                  <a class="nav-link dropdown-toggle py-1"
                     href="#"
                     id="navbarDropdown"
                     role="button"
                     data-bs-toggle="dropdown"
                     aria-expanded="false">
                    <img src="{% if user.image %}{{ user.image.url }}{% else %}{% static "vendor/img/user-image-placeholder.png" %}{% endif %}" alt="User Avatar" class="rounded-circle" width="30" height="30" />
                  </a>
                  <ul class="dropdown-menu dropdown-menu-end"
                      aria-labelledby="navbarDropdown">
                    <li>
                      <a class="dropdown-item" href="{% url "users:profile" %}">Профиль</a>
                    </li>
                    {% if user.is_superuser %}
                      <li>
                        <a class="dropdown-item" href="{% url "admin:index" %}">Админ-панель</a>
                      </li>
                    {% endif %}
                    <li>
                      <hr class="dropdown-divider" />
                    </li>
                    <li>
                      <a class="dropdown-item" href="{% url "users:logout" %}">Выйти</a>
                    </li>
                  </ul>
                </div>
              </li>
              <hr class="bg-dark border-2 border-top border-dark d-flex d-lg-none" />
              <li class="nav-item d-block d-lg-none">
                <p class="my-2">Привет, {{ user.username }}!</p>
              </li>
              <li class="nav-item d-block d-lg-none">
                <a href="{% url "users:profile" %}" class="nav-link">Профиль</a>
              </li>
              {% if user.is_superuser %}
                <li class="nav-item d-block d-lg-none">
                  <a href="{% url "admin:index" %}" class="nav-link">Админ-панель</a>
                </li>
              {% endif %}
              <li class="nav-item d-block d-lg-none">
                <a href="{% url "users:logout" %}" class="nav-link">Выйти</a>
              </li>
            </ul>
          {% else %}
            <ul class="navbar-nav mb-2 mb-lg-0 ms-auto">
              <li class="nav-item d-none d-lg-block">
                <a href="{% url "users:login" %}" class="nav-link">Вход</a>
              </li>
              <li class="nav-item d-none d-lg-block">
                <a href="{% url "users:register" %}" class="btn btn-purple">Регистрация</a>
              </li>
              <hr class="bg-dark border-2 border-top border-dark d-flex d-lg-none" />
              <li class="nav-item d-flex d-lg-none mt-1">
                <a href="{% url "users:login" %}" class="nav-link">Вход</a>
                <a href="{% url "users:register" %}" class="btn btn-purple ms-2">Регистрация</a>
              </li>
            </ul>
          {% endif %}
        </div>
      </div>
    </nav>
    {% block content %}
    {% endblock content %}
    <!-- Footer -->
    <footer class="border-top text-light py-4 mt-auto">
      <div class="container text-center text-secondary">
        <p>© 2024 Wheesh. Все права защищены.</p>
      </div>
    </footer>
    <!-- Bootstrap JS and FontAwesome -->
    <script src="{% static "vendor/fontawesome/fontawesome-icons.js" %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

wheesh/wishlists/templates/wishlists/edit_item.html
{% extends "wishlists/base.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static "vendor/css/new_item.css" %}" />
{% endblock css %}
{% block content %}
    <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card shadow border-0">
                    <div class="card-body p-4">
                        {% if form.errors %}<div class="alert alert-danger">{{ form.errors }}</div>{% endif %}
                        <form action='{% url 'wishlists:edit_item' present.id %}'
                              method='post'
                              enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="mb-3 text-center">
                                <img id="present-pic" src="{% if present.image %}{{ present.image.url }}{% else %}{% static "vendor/img/present-placeholder.png" %}{% endif %}" alt="Present Image" class="rounded mb-3" width="150" height="150" />
                                <div class="mb-2">{{ form.image }}</div>
                            </div>
                            <div class="mb-3">
                                <div class="mb-3">
                                    <label for="{{ form.title.id_for_label }}" class="form-label">Название подарка</label>
                                    {{ form.title }}
                                </div>
                            </div>
                            <div class="mb-3">
                                <div class="mb-3">
                                    <label for="{{ form.description.id_for_label }}" class="form-label">Краткое пожелание (опционально)</label>
                                    {{ form.description }}
                                </div>
                            </div>
                            <div class="mb-3">
                                <div class="mb-3">
                                    <label for="{{ form.link.id_for_label }}" class="form-label">Ссылка на подарок</label>
                                    {{ form.link }}
                                </div>
                            </div>
                            <div class="mb-3">
                                <div class="mb-3">
                                    <label for="{{ form.price.id_for_label }}" class="form-label">Цена (руб.)</label>
                                    {{ form.price }}
                                </div>
                            </div>
                            <!-- Save button -->
                            <div class="d-grid">
                                <button type="submit" class="btn btn-purple mb-2">Сохранить изменения</button>
                                <a href='{% url "wishlists:delete_item" present.id %}'
                                   type="submit"
                                   class="btn btn-danger">Удалить</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block scripts %}
    <script>
  function previewImage(event) {
    const reader = new FileReader();
    reader.onload = function () {
      const output = document.getElementById("present-pic");
      output.src = reader.result;
    };
    reader.readAsDataURL(event.target.files[0]);
  }
    </script>
{% endblock scripts %}

wheesh/wishlists/templates/wishlists/index.html
{% extends "wishlists/base.html" %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static "vendor/css/index.css" %}" />
{% endblock css %}
{% block content %}
  <div class="container-lg my-4 text-center">
    <h1 class="display-5 fw-bold">Добро пожаловать на Wheesh</h1>
    <p class="lead text-secondary mb-4">Идеальная платформа для создания и обмена вишлистами. С кем угодно.</p>
    <p class="h5 mb-4">
      Wheesh создан для того, чтобы вы могли легко создавать вишлисты к любому
      событию — дню рождения, празднику или даже просто так! Делитесь своими
      желаниями с близкими и упрощайте процесс выбора подарков.
    </p>
    {% if user.is_authenticated %}
      <a href="{% url "wishlists:personal" %}"
         class="btn btn-purple btn-lg mb-4">Мой вишлист</a>
    {% else %}
      <a href="{% url "users:register" %}" class="btn btn-purple btn-lg mb-4">Начать сейчас</a>
    {% endif %}
    <div class="custom-divider"></div>
    <!-- Highlight Section -->
    <div class="highlight-section my-5">
      <h2 class="mb-4">Преимущества платформы</h2>
      <div class="row g-4">
        <div class="col-md-4 d-flex align-items-stretch">
          <div class="p-4 rounded feature-card h-100 d-flex flex-column">
            <i class="fas fa-hand-holding-heart icon-feature mb-3"></i>
            <h5>
              <b>Бронирование подарков</b>
            </h5>
            <p>
              Ваши друзья могут забронировать подарок, исключая дублирование и
              облегчая выбор.
            </p>
          </div>
        </div>
        <div class="col-md-4 d-flex align-items-stretch">
          <div class="p-4 rounded feature-card h-100 d-flex flex-column">
            <i class="fas fa-lock icon-feature mb-3"></i>
            <h5>
              <b>Конфиденциальные списки</b>
            </h5>
            <p>
              Ваши списки желаний видны только авторизованным пользователям.
              Полная приватность!
            </p>
          </div>
        </div>
        <div class="col-md-4 d-flex align-items-stretch">
          <div class="p-4 rounded feature-card h-100 d-flex flex-column">
            <i class="fas fa-gift icon-feature mb-3"></i>
            <h5>
              <b>Эффект сюрприза</b>
            </h5>
            <p>
              Вы не увидите, какой подарок забронирован. Сохраните магию
              неожиданности!
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

wheesh/wishlists/templates/wishlists/personal_wishlist.html
{% extends "wishlists/base.html" %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static "vendor/css/wishlist.css" %}" />
{% endblock css %}
{% block content %}
  <div class="container-lg my-4">
    <div class="row d-flex align-items-center justify-content-between mb-4 d-none d-lg-flex">
      <div class="col-auto">
        <p class="h4 text-secondary">{{ wishlist_instance.title }}</p>
      </div>
      <div class="col-auto">
        <button class="btn btn-purple" onclick="copyLink('{{ request.get_host|add:"/"|add:wishlist_instance.slug_url }}', this)">
          Поделиться
        </button>
      </div>
    </div>
    <div class="d-flex d-lg-none mb-4">
      <button class="btn btn-purple w-100" onclick="copyLink('{{ request.get_host|add:"/"|add:wishlist_instance.slug_url }}')">
        Поделиться
      </button>
    </div>
    <div class="row">
      <div class="col-sm-12 col-md-6 col-lg-3 mb-4">
        <a href="{% url "wishlists:new_item" %}" class="add-new-card-link">
          <div class="card h-100 card-transition add-new-card">
            <div class="card-body d-flex justify-content-center align-items-center">
              <i class="fas fa-plus fa-5x text-secondary"></i>
            </div>
          </div>
        </a>
      </div>
      {% for present in wishlist %}
        <div class="col-sm-12 col-md-6 col-lg-3 mb-4">
          <div class="card h-100 card-transition">
            <a href="{% url "wishlists:edit_item" present.id %}"
               class="btn btn-sm btn-light edit-btn position-absolute top-0 end-0 me-2 mt-2 opacity-75">
              <i class="fa-solid fa-pen fas icon-feature text-secondary"></i>
            </a>
            <a href="{% url "wishlists:edit_item" present.id %}"
               class="btn btn-sm btn-light edit-btn position-absolute top-0 end-0 me-2 mt-2 opacity-75 d-inline-block d-lg-none">
              <i class="fa-solid fa-pen fas icon-feature text-secondary"></i>
            </a>
            <div class="card-img-container">
              <img src="{% if present.image %}{{ present.image.url }}{% else %}{% static "vendor/img/present-placeholder.png" %}{% endif %}" class="card-img" alt="Card4" height="100%" width="100%" />
            </div>
            <div class="card-body d-flex flex-column">
              <h5 class="card-title">{{ present.title }}</h5>
              {% if present.description %}
                <p class="card-text">{{ present.description }}</p>
              {% else %}
                <p class="card-text text-secondary">Нет описания</p>
              {% endif %}
              <div class="mt-auto">
                <a href="{{ present.link }}"
                   class="btn btn-purple"
                   target="_blank"
                   data-price="{{ present.price }}"
                   data-original-text="Ссылка">Ссылка</a>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock content %}
{% block scripts %}
  <script type="text/javascript" src="{% static "vendor/js/personal_wishlist.js" %}"></script>
{% endblock scripts %}

wheesh/wishlists/templates/wishlists/reservations.html
{% extends "wishlists/base.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static "vendor/css/reservations.css" %}" />
{% endblock css %}
{% block content %}
    <div class="container-lg mb-4">
        {% if wishlists %}
            {% for wishlist in wishlists %}
                <div class="highlight-section mt-4">
                    <a href="{% url 'wishlists:other' wishlist.slug_url %}"
                       class="text-decoration-none">
                        <h2 class="mb-4 text-secondary">{{ wishlist.title }} [{{ wishlist.user }}]</h2>
                    </a>
                    <div class="overflow-auto pb-2">
                        <div class="row flex-nowrap g-4">
                            {% for present in wishlist.reserved_presents %}
                                <div class="col-sm-12 col-md-6 col-lg-3">
                                    <div class="card h-100 card-transition">
                                        <a href="{% url "wishlists:manage_reservation" present.id %}"
                                           class="btn btn-sm btn-light edit-btn position-absolute top-0 end-0 me-2 mt-2 opacity-75">
                                            <i class="fa-solid fa-minus fas icon-feature text-secondary"></i>
                                        </a>
                                        <a href="{% url "wishlists:manage_reservation" present.id %}"
                                           class="btn btn-sm btn-light edit-btn position-absolute top-0 end-0 me-2 mt-2 opacity-75 d-inline-block d-lg-none">
                                            <i class="fa-solid fa-minus fas icon-feature text-secondary"></i>
                                        </a>
                                        <div class="card-img-container">
                                            <img src="{% if present.image %}{{ present.image.url }}{% else %}{% static "vendor/img/present-placeholder.png" %}{% endif %}" class="card-img" alt="Card4"height="100%" width="100%" />
                                        </div>
                                        <div class="card-body d-flex flex-column">
                                            <h5 class="card-title">{{ present.title }}</h5>
                                            {% if present.description %}
                                                <p class="card-text">{{ present.description }}</p>
                                            {% else %}
                                                <p class="card-text text-secondary">Нет описания</p>
                                            {% endif %}
                                            <div class="mt-auto">
                                                <a href="{{ present.link }}"
                                                   class="btn btn-purple"
                                                   target="_blank"
                                                   data-price="1000"
                                                   data-original-text="Ссылка">Ссылка</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="col-sm-12 text-center mt-4">
                <p class="text-secondary mb-1">Пусто...</p>
                <p class="text-secondary mb-1">( o.o)</p>
            </div>
        {% endif %}
    </div>
{% endblock content %}